food/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .import views

#app_name for food's urls.py
app_name= 'food'
urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('item/', views.item, name='item'),

    #/food/1   dispay single item
    path('<int:itemId>/', views.detail, name='detail'),
    #add item to the list 
    path('addItem/', views.addItem, name='addItem'), 
    #edit item
    path('update/<int:itemId>/',views.updateItem, name='updateItem'),
    #delete item
    path('delete/<int:itemId>/', views.deleteItem, name='deleteItem'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #if any url req comes with food send it to food.urls
    path('food/',include('food.urls')),
]

food/models.py
from django.db import models

# Create your models here.




class Item(models.Model):
    def __str__(self):
        return self.itemName

    itemName= models.CharField(max_length=200)
    itemDescription= models.CharField(max_length=1000)
    itemPrice= models.IntegerField()
    itemImage= models.CharField(max_length=500, default="https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg")
    

food/views.py
from food.addforms import ItemForm
from django import forms, template
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Item
from django.template import context, loader

# Create your views here.
def index(request):
    item_list= Item.objects.all()
    template= loader.get_template('food/index.html')
    context={
        'itemList': item_list,
    }
    return HttpResponse(template.render(context, request))                                                                                                                                                                                                                                       

def item(request):
    return HttpResponse('Hello to the item! O_O ')


def detail(request, itemId):
    item= Item.objects.get(pk=itemId)
    context={
        'item': item,
   
    }
    template= loader.get_template('food/detail.html')
    #return HttpResponse('this is the id %s' %itemId)
    return render(request, 'food/detail.html', context)

def addItem(request):
    form= ItemForm(request.POST or None)
    #validation
    if form.is_valid():
        form.save()
        return redirect('food:index')

    template= loader.get_template('food/addItem.html')
    return HttpResponse(template.render({'form':form}, request))

def updateItem(request, itemId):
    item= Item.objects.get(id=itemId);
    #iniialize form and pass the data of selected item to the form
    form= ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save();
        return redirect('food:index')

    #load templete and return on single line
    return render(request, 'food/addItem.html', {'form':form, 'item':item})

def deleteItem(request, itemId):
    item= Item.objects.get(id=itemId);
    
    #if request.method== 'POST':
    item.delete();
    return redirect ('food:index')

    #return HttpResponse('Deleted!')
    #added this ro directly delte the item

food/templates/food/addItem.html
{% extends 'food/base.html' %}

{% block body %}




<div> 

    <h3> Add food to the App </h3>

    <form method="POST">
        {% csrf_token %}

        {{ form }}

        <button type="submit" name="" id="" class="btn btn-primary btn-lg btn-block">Save </button>
    </form>


    
</div>




{% endblock body %}

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}"> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Document101</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Food</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="/food/index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/food/addItem">Add Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Delete Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">View Item</a>
                </li> 
            </ul>
        </div>
    </nav>

    {% block body %}
    
    {% endblock body %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% block body %}

    <div class="container"> 
        <div>
            <h2> {{ item.itemName }} </h2><br>

        </div>

        <img src="{{item.itemImage}}" height="250px"/>
        
        <p><h4>
            Item ID: {{item.id}} <br>
            Item Name: {{ item.itemName }} <br>
            Item Details: {{ item.itemDescription }} <br>
            Price: {{ item.itemPrice }}$$ <br>
            </h4>
        </p>
        <a name="" id="" class="btn btn-primary" href="{% url 'food:updateItem' item.id %}" role="button">
        Update Item</a>

        <a name="" id="" class="btn btn-primary danger" href="{% url 'food:deleteItem' item.id %}" role="button">
        Delete Item</a>
    </div>
    
{% endblock body %}


</body>
</html>

food/templates/food/index.html
{% extends 'food/base.html' %}

    {% block body %}

        <h1>This is the template for index of food app! 101 </h1>

        {% for item in itemList %}
            </br>
            <div class="row">
                <div class="col-md-1 offset-md-1">
                    {{ item.id }} <br>

                </div>

                <div class="col-md-3">
                    <br>
                    <h3> {{ item.itemName }} </h3> <br>
                    {{ item.itemDescription}} <br>
                    {{ item.itemPrice}} <br>
                </div>


                <div class="col-md-2">
                    <img class="card" height="150px" src="{{item.itemImage}}"/>
                </div>

                <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}">
                <button type="button" name="" id="" class="btn btn-primary" btn-lg btn-block> 
                View Details</button>
                </a>
                </div>
            </div> 

            
        {% endfor %}

    {% endblock body %}